# -*- coding: utf-8 -*-
"""Database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9ONcHRUWdsZzHiVkETXF5RnbmwnURBo
"""

from pymongo import MongoClient

client = MongoClient('localhost', 27017)
db = client['restaurante']
colecao_comidas = db['comidas']
colecao_clientes = db['clientes']
colecao_vendas = db['vendas']